 $(document).ready(function () {
      $('.owl-carousel').owlCarousel();
    });

    $('.activism-carousel').owlCarousel({
    loop:true,
    margin:10,
    responsive:{
        0:{
            items:1.5
        },
        768:{
            items:2.5
        },
        992:{
            items:5
        }
    }
    })

    $('.blog-carousel').owlCarousel({
    loop:true,
    margin:10,
    responsive:{
        0:{
            items:1.5
        },
        768:{
            items:2.5
        },
        992:{
            items:4
        }
    }
    })

    $('.workshops-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1.5
        },
        768:{
            items:2.5
        },
        992:{
            items:1
        }
    }
    })

    $('.projects-carousel').owlCarousel({
        loop:true,
        margin:10,
        nav:true,
        responsive:{
            0:{
                items:1.5
            },
            768:{
                items:2.5
            },
            992:{
                items:1
            }
        }
        })
